name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fix Playwright Permissions
        run: chmod +x ./node_modules/.bin/playwright

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npm run test:playwright

      - name: Create Playwright Test Report (ZIP)
        run: zip -r playwright-report.zip playwright-report/

      - name: Upload Playwright Report ZIP
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-zip
          path: playwright-report.zip

      - name: Extract HTML Report from ZIP
        run: |
          mkdir -p extracted-report
          unzip playwright-report.zip -d extracted-report
          # Assuming the HTML report is named 'index.html' or adjust accordingly
          mv extracted-report/path/to/index.html extracted-report/index.html

      - name: Upload HTML Report to GitHub Pages (or Raw GitHub Content)
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: extracted-report/index.html

      - name: Post Playwright Report Link as Comment
        if: github.event_name == 'pull_request' # Ensures it's only run for PRs
        uses: actions/github-script@v6
        with:
          script: |
            const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/artifacts`;
            const reportUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/raw/main/extracted-report/index.html`;  # Update with the correct URL
            const commentBody = `Playwright test report is available. [View the report here](${reportUrl}).`;
            const prNumber = context.payload.pull_request?.number;
            if (prNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody
              });
            } else {
              console.log("No pull request context available.");
            }
