name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fix Playwright Permissions
        run: chmod +x ./node_modules/.bin/playwright

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npm run test:playwright

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Post Playwright Report Link as Comment
        if: github.event_name == 'pull_request' # Ensures it's only run for PRs
        uses: actions/github-script@v6
        with:
          script: |
            const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/artifacts`;
            const commentBody = `Playwright test report is available as an artifact. [Download the report here](${artifactUrl}).`;
            const prNumber = context.payload.pull_request?.number;
            if (prNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody
              });
            } else {
              console.log("No pull request context available.");
            }
